services:

  db:
    image: postgres:15.2
    container_name: to-do-list
    restart: always
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - "5432:5432"